name: Terraform

on:
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest

  steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.1.7"

    - name: Initialize Terraform
      uses: terraform init


