name: Terraform

on:
  pull_request:
     types: [opened, reopened]

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure GCP Credentials
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/1025759812276/locations/global/workloadIdentityPools/github/providers/my-rep
          service_account: github-workload-identifier-sa@cloudrun-test-415115.iam.gserviceaccount.com

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.1.7"

      - name: Initialize Terraform
        run: terraform init
